Models/CalendarEvent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Outlook_Calendar_Test.Models
{
    public class CalendarEvent
    {
        public CalendarEvent()
        {
            this.Body = new Body()
            {
                ContentType = "html"
            };
            this.Start = new EventDateTime()
            {
                TimeZone = "Eastern Standard Time"
            };
            this.End = new EventDateTime()
            {
                TimeZone = "Eastern Standard Time"
            };
        }
        public string Subject { get; set; }

        public Body Body { get; set; }

        public EventDateTime Start { get; set; }

        public EventDateTime End { get; set; }


    }

    public class Body
    {
        public string ContentType { get; set; }

        public string Content { get; set; }
    }

    public class EventDateTime
    {
        public DateTime Datetime { get; set; }
        public string TimeZone { get; set; }
    }

}

Controllers/CalendarController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Outlook_Calendar_Test.Models;
using RestSharp;
using System;
using System.Web.Mvc;

namespace Outlook_Calendar_Test.Controllers
{
    public class CalendarController : Controller
    {
        string tokensFile = "C:\\Users\\alk22\\source\\repos\\Outlook Calendar Test\\files\\tokens.json";

        public ActionResult CreateEvent(CalendarEvent calendarEvent)
        {
            JObject tokens = JObject.Parse(System.IO.File.ReadAllText(tokensFile));

            RestClient restClient = new RestClient();
            RestRequest restRequest = new RestRequest();

            restRequest.AddHeader("Authorization", "Bearer " + tokens["access_token"].ToString());
            restRequest.AddHeader("Content-Type", "application/json");
            restRequest.AddParameter("application/json", JsonConvert.SerializeObject(calendarEvent), ParameterType.RequestBody);

            restClient.BaseUrl = new Uri("https://graph.microsoft.com/v1.0/me/calendar/events");
            var response = restClient.Post(restRequest);

            if(response.StatusCode == System.Net.HttpStatusCode.Created)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Error");
        }

        public ActionResult Index()
        {
            return View();
        }


    }
}

Controllers/HomeController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Outlook_Calendar_Test.Controllers
{
    public class HomeController : Controller
    {
        string credentialsFile = "C:\\Users\\alk22\\source\\repos\\Outlook Calendar Test\\files\\credentials.json";
        string adminCredentialsFile = "C:\\Users\\alk22\\source\\repos\\Outlook Calendar Test\\files\\admincredentials.json";

        public ActionResult Index()
        {
            return View();
        }

 
        
        public ActionResult OauthRedirect()
        {
            JObject credentials = JObject.Parse(System.IO.File.ReadAllText(credentialsFile));
            var redirectUrl = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize?" +
                              "&scope=" + credentials["scopes"].ToString() +
                              "&response_type=code" +
                              "&response_mode=query" +
                              "&state=alk228" +
                              "&redirect_uri=" + credentials["redirect_url"].ToString() +
                              "&client_id=" + credentials["client_id"].ToString();
            return Redirect(redirectUrl);
        }

        public ActionResult AdminOauthRedirect()
        {
            JObject credentials = JObject.Parse(System.IO.File.ReadAllText(adminCredentialsFile));

            var redirectUrl = "https://login.microsoftonline.com/common/adminconsent?"+
                              "&state=alk228" +
                              "&redirect_uri=" +credentials["redirect_url"].ToString()+
                              "&client_id=" + credentials["client_id"].ToString();

            return Redirect(redirectUrl);
        }
    }
}

Controllers/OauthController.cs
using Newtonsoft.Json.Linq;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Outlook_Calendar_Test.Controllers
{
    public class OauthController : Controller
    {
        string credentialsFile = "C:\\Users\\alk22\\source\\repos\\Outlook Calendar Test\\files\\credentials.json";
        string tokensFile = "C:\\Users\\alk22\\source\\repos\\Outlook Calendar Test\\files\\tokens.json";
        string adminCredentialsFile = "C:\\Users\\alk22\\source\\repos\\Outlook Calendar Test\\files\\admincredentials.json";


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Callback(string code, string state, string error)
        {
            JObject credentials = JObject.Parse(System.IO.File.ReadAllText(credentialsFile));

            if(!string.IsNullOrWhiteSpace(code))
            {
                RestClient restClient = new RestClient();
                RestRequest restRequest = new RestRequest();

                restRequest.AddParameter("client_id", credentials["client_id"].ToString());
                restRequest.AddParameter("scope", credentials["scopes"].ToString());
                restRequest.AddParameter("redirect_uri", credentials["redirect_url"].ToString());
                restRequest.AddParameter("code", code);
                restRequest.AddParameter("grant_type", "authorization_code");
                restRequest.AddParameter("client_secret", credentials["client_secret"].ToString());

                restClient.BaseUrl = new Uri("http://login.microsoftonline.com/common/oauth2/v2.0/token");
                var response = restClient.Post(restRequest);

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    System.IO.File.WriteAllText(tokensFile, response.Content);
                    return RedirectToAction("Index", "Home");
                }

            }
            return RedirectToAction("Error");
        }

        public ActionResult AdminCallback(string tenant, string state, string admin_consent)
        {
            JObject credentials = JObject.Parse(System.IO.File.ReadAllText(adminCredentialsFile));

            if(!string.IsNullOrWhiteSpace(tenant))
            {
                RestClient restClient = new RestClient();
                RestRequest restRequest = new RestRequest();

                restRequest.AddParameter("client_id", credentials["client_id"].ToString());
                restRequest.AddParameter("scope", credentials["scopes"].ToString());
                restRequest.AddParameter("grant_type", "client_credentials");
                restRequest.AddParameter("client_secret", credentials["client_secret"].ToString());

                restClient.BaseUrl = new Uri($"https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token");
                var response = restClient.Post(restRequest);

                if(response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    System.IO.File.WriteAllText(tokensFile, response.Content);
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Error");
        }

        public ActionResult RefreshToken()
        {
            JObject credentials = JObject.Parse(System.IO.File.ReadAllText(credentialsFile));
            JObject tokens = JObject.Parse(System.IO.File.ReadAllText(tokensFile));

            RestClient restClient = new RestClient();
            RestRequest restRequest = new RestRequest();

            restRequest.AddParameter("client_id", credentials["client_id"].ToString());
            restRequest.AddParameter("grant type", "refresh_token");
            restRequest.AddParameter("scope", credentials["scopes"].ToString());
            restRequest.AddParameter("refresh_token", tokens["refresh_token"].ToString());
            restRequest.AddParameter("redirect_uri", credentials["redirect_url"].ToString());
            restRequest.AddParameter("client_secret", credentials["client_secret"].ToString());

            restClient.BaseUrl = new Uri($"https://login.microsoftonline.com/common/oauth2/v2.0/token");
            var response = restClient.Post(restRequest);

            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                System.IO.File.WriteAllText(tokensFile, response.Content);
                return RedirectToAction("Index", "Home");
            }
        
            return RedirectToAction("Error");


    }

        
    }
}

Views/Calendar/CreateEvent.cshtml
<div style="margin-top: 50px;">
    <form method="post" action="Calendar/CreateEvent">
        <div class="row" style="margin=10px;">
            <label for="Summary" class="col-sm-3"> Subject:</label>
            <input type="text" class=" col-sm-1 form-control" name="Subject" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin=10px;">
            <label for="Description" class="col-sm-3"> Content:</label>
            <input type="datetime" class=" col-sm-1 form-control" name="Body.Content" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin=10px;">
            <label for="Start.datetime" class="col-sm-3"> Start Date Time:</label>
            <input type="datetime" class=" col-sm-1 form-control" name="Start.datetime" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin=10px;">
            <label for="End.datetime" class="col-sm-3"> End Date Time:</label>
            <input type="datetime" class=" col-sm-1 form-control" name="End.datetime" value="" autocomplete="off" />
        </div>
        <div class="row col-sm-3" style="margin:10px;">
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<button class=" btn btn-primary" style="margin-top: 20px;" onclick="location.href = '@Url.Action("OauthRedirect", "Home")'">Sign In</button>

<button class=" btn btn-primary" style="margin-top: 20px; margin-left: 10px;" onclick="location.href = '@Url.Action("RefreshToken", "Oauth")'">Refresh Access Token</button>

<button class=" btn btn-primary" style="margin-top: 20px; margin-left: 10px;" onclick="location.href = '@Url.Action("AdminOauthRedirect", "Home")'">Admin Sign In</button>

<div style="margin-top: 50px;">
    <form method="post" action="Calendar/CreateEvent">
        <div class="row" style="margin=10px;">
            <label for="Summary" class="col-sm-3"> Subject:</label>
            <input type="text" class=" col-sm-1 form-control" name="Subject" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin=10px;">
            <label for="Description" class="col-sm-3"> Content:</label>
            <input type="datetime" class=" col-sm-1 form-control" name="Body.Content" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin=10px;">
            <label for="Start.datetime" class="col-sm-3"> Start Date Time:</label>
            <input type="datetime" class=" col-sm-1 form-control" name="Start.datetime" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin=10px;">
            <label for="End.datetime" class="col-sm-3"> End Date Time:</label>
            <input type="datetime" class=" col-sm-1 form-control" name="End.datetime" value="" autocomplete="off" />
        </div>
        <div class="row col-sm-3" style="margin:10px;">
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>